# Generated by Django 2.1.5 on 2019-04-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('', '-----'), (1, 'Guitar'), (2, 'Blockchain'), (3, 'Flute')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
