# Generated by Django 2.1.5 on 2019-04-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Discussion', '0003_auto_20190420_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateField(auto_now_add=True, db_index=True)),
                ('cbody', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('', '-----'), ('1', 'Guitar'), ('2', 'Blockchain'), ('3', 'Flute')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='cpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
